export const CONTACT_EMAIL = 'kochkinaea83@gmail.com'
export const EXCHANGE_RATE_API_URL = 'https://nbs-rates.gudrum1983.workers.dev/api/v1/currencies'
export const EXCHANGE_RATE_SITE_URL = 'https://kurs.resenje.org/'
export const NBS_SITE_URL = 'https://www.nbs.rs/en'
export const SRB_GUIDE_KPO_URL = 'https://www.srb.guide/guides/business/tax/#%d0%ba%d0%bd%d0%b8%d0%b3%d0%b0-kpo'
