export const MOCK = [
  {
    date: '2024-01-12',
    description: 'Продажа товара',
    counterparty: 'ООО Альфа',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'EUR',
    incomeFromProductsCurrencyAmount: '105,40',
    incomeFromProducts: '12 500',
    incomeFromServicesCurrency: 'EUR',
    incomeFromServicesCurrencyAmount: '0,00',
    incomeFromServices: '0',
    totalIncomeCurrency: 'EUR',
    totalIncomeCurrencyAmount: '105,40',
    totalIncome: '12 500',
  },
  {
    date: '2024-01-15',
    description: 'Услуги консультации',
    counterparty: 'ИП Никитин',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'USD',
    incomeFromProductsCurrencyAmount: '0,00',
    incomeFromProducts: '0',
    incomeFromServicesCurrency: 'USD',
    incomeFromServicesCurrencyAmount: '88,20',
    incomeFromServices: '8 200',
    totalIncomeCurrency: 'USD',
    totalIncomeCurrencyAmount: '88,20',
    totalIncome: '8 200',
  },
  {
    date: '2024-01-21',
    description: 'Смешанный доход',
    counterparty: 'ЗАО Бета',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'CHF',
    incomeFromProductsCurrencyAmount: '40,00',
    incomeFromProducts: '4 000',
    incomeFromServicesCurrency: 'CHF',
    incomeFromServicesCurrencyAmount: '30,00',
    incomeFromServices: '3 000',
    totalIncomeCurrency: 'CHF',
    totalIncomeCurrencyAmount: '70,00',
    totalIncome: '7 000',
  },
  {
    date: '2024-01-28',
    description: 'Крупная партия товара',
    counterparty: 'ООО Магистраль',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'EUR',
    incomeFromProductsCurrencyAmount: '10 550,50',
    incomeFromProducts: '1 250 000,50',
    incomeFromServicesCurrency: 'EUR',
    incomeFromServicesCurrencyAmount: '0,00',
    incomeFromServices: '0,00',
    totalIncomeCurrency: 'EUR',
    totalIncomeCurrencyAmount: '10 550,50',
    totalIncome: '1 250 000,50',
  },
  {
    date: '2024-02-02',
    description: 'Долгосрочное обслуживание',
    counterparty: 'ИП Белова',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'USD',
    incomeFromProductsCurrencyAmount: '0,00',
    incomeFromProducts: '0,00',
    incomeFromServicesCurrency: 'USD',
    incomeFromServicesCurrencyAmount: '19 900,75',
    incomeFromServices: '2 340 000,75',
    totalIncomeCurrency: 'USD',
    totalIncomeCurrencyAmount: '19 900,75',
    totalIncome: '2 340 000,75',
  },
  {
    date: '2024-02-06',
    description: 'Суммарный оборот',
    counterparty: 'ОАО Вектор',
    incomeCurrency: 'дин',
    incomeFromProductsCurrency: 'GBP',
    incomeFromProductsCurrencyAmount: '4 250,00',
    incomeFromProducts: '500 000,00',
    incomeFromServicesCurrency: 'GBP',
    incomeFromServicesCurrencyAmount: '6 380,00',
    incomeFromServices: '750 000,00',
    totalIncomeCurrency: 'GBP',
    totalIncomeCurrencyAmount: '10 630,00',
    totalIncome: '1 250 000,99',
  },
]
